package freecatalog

import (
	"os"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

type providerFreeTierDoc struct {
	FormatVersion int      `yaml:"format_version"`
	EffectiveDate string   `yaml:"effective_date"`
	Models        []string `yaml:"models"`
	Patterns      []string `yaml:"patterns,omitempty"`
}

// WriteProviderFreeTierYAML writes gateway config/provider-free-tier.yaml shape:
// intersected groq/gemini model ids plus optional patterns (e.g. ollama/*).
func WriteProviderFreeTierYAML(path string, effectiveDate time.Time, entries []Entry, extraPatterns []string) error {
	byID := make(map[string]struct{})
	for _, e := range entries {
		id := strings.TrimSpace(e.BiFrostID)
		if id != "" {
			byID[id] = struct{}{}
		}
	}
	models := make([]string, 0, len(byID))
	for id := range byID {
		models = append(models, id)
	}
	sort.Strings(models)

	patterns := dedupePatterns(extraPatterns)

	doc := providerFreeTierDoc{
		FormatVersion: 1,
		EffectiveDate: effectiveDate.UTC().Format("2006-01-02"),
		Models:        models,
		Patterns:      patterns,
	}
	var b strings.Builder
	b.WriteString("# Generated by: make config-provider-free-tier (or go run ./cmd/catalog-write-free -provider-free-tier-out ...)\n")
	b.WriteString("# Merge or replace config/provider-free-tier.yaml; routing uses live GET /v1/models ∩ this allowlist.\n\n")
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return nil
}

func dedupePatterns(in []string) []string {
	seen := make(map[string]struct{})
	var out []string
	for _, p := range in {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if _, ok := seen[p]; ok {
			continue
		}
		seen[p] = struct{}{}
		out = append(out, p)
	}
	return out
}
